required = [
  "github.com/go-ini/ini", # For github.com/aws/aws-sdk-go-v2/aws/external/shared_config.go
  "golang.org/x/net/html", # For github.com/aws/aws-sdk-go-v2/private/model/api/docstring.go
]

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "2.0.0-preview.3"
